[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
hypergraph = "^2.1.2"
egui_graphs = "^0.22.0"
eframe = "^0.29.1"

#egui_graphs = { version = "0.22", features = ["egui_persistence"]}
#egui = {version="0.29", features = ["persistence"]}